version: 2.1
 
orbs:
  android: circleci/android@1.0.3
  vulnachecka: whitesource/vulnerability-checker@19.5.5
  prettier: cfra/prettier@0.1.1
  codecov: codecov/codecov@1.2.3
 
jobs:
  build:
    executor: android/android
    steps:
      - codecov/upload:
          file: coverage.xml
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  test:
    jobs:
      - vulnachecka/scan
      
  build:
    jobs:
      - prettier/check
      - prettier/write-commit-push
